{
    'name': 'Despacho Rolda',
    'version': '13.0.0.0.1',
    'depends': ['rolda', 'stock', 'account', 'sale_management'],
    'author': 'Keiver Peña',
    'license': 'AGPL-3',
    'website': 'https://gitlab.com/keiverobles',
    'category': 'Libros Fiscales-Accounting',
    'data': [
        'security/ir.model.access.csv',
        'data/sequence_data.xml',
        'wizard/print_guide_views.xml',
        'views/assets.xml',
        'views/despacho_views.xml',
        'views/sale_order_views.xml',
        'views/res_partner_views.xml',
        'report/report_guide_consolidated_templates.xml',
        'report/report_guide_detailed_templates.xml',
        'report/report_guide_customer_templates.xml',
        'report/report_guide_farmatodo_templates.xml',
        'report/report_templates.xml',
        'report/despacho_rolda_reports.xml',
    ],
    'installable': True,
}
