{
    'name': 'Rolda',
    'version': '13.0.0.2.1',
    'author': 'Keiver Peña',
    'license': 'AGPL-3',
    'website': 'https://gitlab.com/keiverobles',
    'category': 'Libros Fiscales-Accounting',
    'depends': [
        'locv_fiscal_book',
        'locv_withholding_iva',
        'locv_account_fiscal_requirements',
        'l10n_ve_dpt',
        'mrp',
    ],
    'data': [
        'security/ir.model.access.csv',
        # ~ 'data/company_data.xml',
        'data/sequence_data.xml',
        'views/assets.xml',
        'views/invoice_view.xml',
        'views/res_partner_views.xml',
        'views/export_bank_payments_views.xml',
        'views/product_pack_view.xml',
        'report/rolda_reports.xml',
        'report/fiscal_purchase_book_report.xml',
        'report/fiscal_book_report.xml',
        'report/report_invoice.xml',
        'report/withholding_vat_report.xml',
    ],
    'installable': True,
}
